version: '3.3'

services:
    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        env_file:
            - .env_php
        volumes:
            - ./:/var/www:rw
    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        links:
          - php
        ports:
            - 80:80
    db:
        image: mysql:8.0.21
        command: mysqld --default-authentication-plugin=mysql_native_password
        env_file:
            - .env_mysql
        volumes:
            - data:/var/lib/mysql
        ports:
            - 3306:3306
volumes:
    data:
